pipeline {
    agent any
 stages {
        stage('Checkout') {
            steps {
              git branch: 'main', url: 'https://github.com/devsecopsmurali/java-maven-project.git'
           }
        }
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean install' 
            }
        }
 
    }
}
